### ISSUE TITLE
Add more members

### ISSUE THREAD

**Issue by jophab** [RITct/RITct-discussions#2]
We should add more students to this organisation and encourage them to add their projects here.

1. Think about the possible ways to do this

2. Now, only the owners of this org can create a repository here. Each repo is exclusively for a single project..We should move all projects to a single folder or more than one folders according to their categories, so that other members can create repos for their project after cloning the corresponding category folder.

**Comment by ParadoxZero** [comment]
The problem is the lack of people who use GitHub. Even if they have
account. Not many know how to use it, unless we conduct some getting
started program at it department, which sounds not bad.

**Comment by gautamkrishnar** [comment]
* I think forking the student project would be the best option. It will maintain the project's  ownership.
* We cannot use single folder for specific groups, it will not follow the correct git workflow.
* People can create repo in the org if they want. It is currently enabled in the org's settings. Any of the org owner can give them write access to the repo if needed.

Currently the org owners are @Aksh77 @ParadoxZero @jophab @arunkumars3483 @JerrinThomas  and Me

* We can try doing some group projects using the org, For group projects, creating a new team with the project's name would be the best way to collaborate. We can add people to the team and give them write access to the GitHub group project repository.

* I think, while doing group projects it is better to follow the git pull request workflow rather than giving the write access to the repository.

**Comment by ParadoxZero** [comment]
Yes, also there needs a general awareness about git and version control. As of right now, our department doesn't have many developers even though there are many good programmers.

I really recommend some sort of workshop or training. Also, there is a lack of motivation and passion among the majority.

Just getting many members doesn't help. Even right now, out of the 17 members we have, not many are active.

The way I see it, there are fundamentally  **two** problems:

- Students don't know and/or don't have the interest to work on developing stuff.

- Students don't know about version control or git.

I have seen student's using GitHub as a place to just store files, while not exactly bad they aren't using the features which would come really handy.

To get a get an active community going we need to tackle these problems.

**Comment by gautamkrishnar** [comment]
@jophab we need to apply for availing the private repositories for this org. Since me and @ParadoxZero had already used this benefit we cant apply for it again. 

You must try applying for it:
https://education.github.com/discount_requests/new

Select discount for the organization from the option.

**Comment by jophab** [comment]
@gautamkrishnar Request is submitted

**Comment by Abhi1401** [comment]
We need a better name. 
Instead of working in GitHub, it would be better to move organisation to real world to collaborate with more designers. Individual and group projects could be still monitored and shared through this git organisation. But I think we should find other ways for better communications.

**Comment by ParadoxZero** [comment]
Exactly, we need to be active offline. That's the only way I can see right
now.
